language: android

jdk:
 - openjdk8

android:
  components:
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository

  licenses:
    - '.+'

script:
    - ./gradlew clean assemble --stacktrace

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $ANDROID_HOME
