name: "CI builds"
on: [push, pull_request]

jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git fetch --tags
    - run: ./gradlew spotlessCheck assemble check
